Update docker images for Suredbits Wallet
getumbrel/umbrel pull request #1358
Opened 2022-04-20 21:34 UTC by Christewart

2022-05-12 22:09 UTC, nevets963 requested changes
Can you also update the version number within `./apps/registry.json` ?

Otherwise this is good to be merged in.

2022-05-12 22:09 UTC, nevets963 commented on apps/suredbits-wallet/docker-compose.yml
> +    image: bitcoinscala/wallet-server-ui:1.9.1@sha256:34f6f57ffd87b200895a528b37b4fb80c0d508af088753a98dc70740c0d7b93a
Can you change the digest to: `sha256:3eb479b106811d523c4e0cfde244949f6c76a27c7d1fe59be9b8b51ba2372649`

This looks like the digest only for `amd64`, but the above can be used with both `amd64` and `arm64`

2022-05-12 22:09 UTC, nevets963 commented on apps/suredbits-wallet/docker-compose.yml
> +    image: bitcoinscala/bitcoin-s-server:1.9.1-34-3dc70938-SNAPSHOT@sha256:aa491b19b0f2ce6a35e1c7c259e9233a07a1dc49775f994e835dd818f459347b
Can you change the digest to: `sha256:1cd82d19059382f740f7b8acbc2d3aaeaf0c1fd7c662bdbc3ef7b97a27ee181f`

2022-05-13 10:05 UTC, lukechilds commented on apps/suredbits-wallet/docker-compose.yml
> +    image: bitcoinscala/wallet-server-ui:1.9.1@sha256:34f6f57ffd87b200895a528b37b4fb80c0d508af088753a98dc70740c0d7b93a
```suggestion
    image: bitcoinscala/wallet-server-ui:1.9.1@sha256:3eb479b106811d523c4e0cfde244949f6c76a27c7d1fe59be9b8b51ba2372649
```

2022-05-13 10:06 UTC, lukechilds commented on apps/suredbits-wallet/docker-compose.yml
> +    image: bitcoinscala/bitcoin-s-server:1.9.1-34-3dc70938-SNAPSHOT@sha256:aa491b19b0f2ce6a35e1c7c259e9233a07a1dc49775f994e835dd818f459347b
```suggestion
    image: bitcoinscala/bitcoin-s-server:1.9.1-34-3dc70938-SNAPSHOT@sha256:1cd82d19059382f740f7b8acbc2d3aaeaf0c1fd7c662bdbc3ef7b97a27ee181f
```

2022-05-13 10:09 UTC, merged