Update LN markets to v1.2.3
getumbrel/umbrel pull request #1366
Opened 2022-05-03 14:20 UTC by vafanassieff

Hey new update to LNM app that should fix login issue and with a new auth :)

BTW, where can I add our new logo ?

Thanks !

2022-05-03 17:12 UTC, louneskmt commented
Hey, thanks for this PR! Regarding the new logo, you can make a PR to https://github.com/getumbrel/umbrel-apps-gallery.

2022-05-12 21:58 UTC, nevets963 requested changes

2022-05-12 21:58 UTC, nevets963 commented on apps/lnmarkets/docker-compose.yml
> +    image: ghcr.io/ln-markets/umbrel:v1.2.3@sha256:2070b9d8e57f6eb997919e0f52b90033c7492870f0b54c88c590860a67df4704
Can you change the digest to: `sha256:c11ec6d28d1b1d11d82ae8b33916732686a296beb21c9c3eaee80c823bd2d00f`

This digest looks specific to `arm64` but the above is good for `amd64` and `arm64`. Other than that, this is good to be merged in.

2022-05-13 10:00 UTC, lukechilds commented on apps/lnmarkets/docker-compose.yml
> +    image: ghcr.io/ln-markets/umbrel:v1.2.3@sha256:2070b9d8e57f6eb997919e0f52b90033c7492870f0b54c88c590860a67df4704
```suggestion
    image: ghcr.io/ln-markets/umbrel:v1.2.3@sha256:c11ec6d28d1b1d11d82ae8b33916732686a296beb21c9c3eaee80c823bd2d00f
```

2022-05-13 10:21 UTC, lukechilds commented
Hey guys, resolved the issue in https://github.com/getumbrel/umbrel/pull/1380

@vafanassieff in future are you able to submit PRs from a feature branch instead of master so we're able to push changes to it?

2022-05-13 10:21 UTC, closed without merging

2022-05-13 10:29 UTC, vafanassieff commented
@lukechilds Crap, we are always missing something, duly noted !

Thanks for the merge !

2022-05-13 11:20 UTC, lukechilds commented
No worries!