Fix docker-compose output parsing
getumbrel/umbrel pull request #1561
Opened 2022-11-27 13:31 UTC by chokoboko

This PR fixes the case where `docker-compose` `ps` command returns multiline output per container, resulting wrong names being passed down the line.

Tested on Ubuntu 20.04, x86, docker-compose 1.25.0

![umbrl](https://user-images.githubusercontent.com/44872722/204137982-603f94c6-dd67-487e-981c-09a4e23ebc8d.png)

2023-02-23 02:10 UTC, khoangkhac118 approved these changes

2023-02-28 04:36 UTC, khoangkhac118 approved these changes

2023-02-28 04:36 UTC, khoangkhac118 approved these changes

2023-02-28 04:38 UTC, khoangkhac118 requested changes
review-requested:[khoangkhac118]

2023-05-27 04:38 UTC, nmfretz commented
Hey @chokoboko. Thanks for this PR, and sorry for the delay in reviewing.

I see that in your example screenshot you are comparing your suggested change to this command that doesn't do any additional filtering and results in incorrect output:
`./scripts/app compose bitcoin ps | awk '{print $1}'`

But I think the right command to compare it to is actually this command that is currently being used in the script:
`./scripts/app compose bitcoin ps | awk '{print $1}' | grep -v 'Name\|-----'`

I get the same output that you show from your modified command:
```
./scripts/app compose bitcoin ps | awk '{print $1}' | grep -v 'Name\|-----'
bitcoin_app_proxy_1
bitcoin_bitcoind_1
bitcoin_i2pd_daemon_1
bitcoin_server_1
bitcoin_tor_1
```

Am I missing something?

2024-03-19 10:05 UTC, mayankchhabra commented
Thank you for the PR, @chokoboko! With the launch of [umbrelOS 1.0](https://github.com/getumbrel/umbrel/releases/tag/v1.0.0), we've introduced extensive changes to both the source code and the system's architecture. As part of this transition, we're reviewing and closing PRs and issues that might no longer be applicable to the new version. So I'll be closing this PR for now. Thanks again!

2024-03-19 10:05 UTC, closed without merging